### Get XML

GET https://localhost:49256/LoanApplication/xml


### Get Diagram

GET https://localhost:49256/LoanApplication/diagram



########################################################
# Start Loan Application
########################################################

# @name startLoanApplication

POST https://localhost:49256/LoanApplication
Content-Type: application/json

{
    "ApplicantName": "Eric White",
    "LoanAmount": 11000,
    "YearlyGrossSalary": 80000
}


### 

@instanceId = {{startLoanApplication.response.body.*}}

###

GET https://localhost:49256/LoanApplication/{{instanceId}}/diagram


###

POST https://localhost:49256/LoanApplication/{{instanceId}}/RaiseAssessApplicationCompleted
Content-Type: application/json

false

###

POST https://localhost:49256/LoanApplication/{{instanceId}}/RaiseCustomerDecisionCompleted
Content-Type: application/json

true

###

POST https://localhost:49256/LoanApplication/{{instanceId}}/RaiseActivity_1ag39siCompleted
Content-Type: application/json

{
}


### 

POST https://localhost:49256/LoanApplication/{{instanceId}}/RaiseActivity_1mp2kplCompleted
Content-Type: application/json

{
}
