########################################################
# Start Loan Application
########################################################

# @name startLoanApplication

POST https://localhost:49256/LoanApplication
Content-Type: application/json

{
    "ApplicantName": "Eric Grey",
    "LoanAmount": 110000,
    "YearlyGrossSalary": 80000
}


### 

@instanceId = 7dca9cb535b241268e04a58bd2e7883b

###

POST https://localhost:49256/LoanApplication/{{instanceId}}/RaiseAssessApplicationCompleted
Content-Type: application/json

false

###

POST https://localhost:49256/LoanApplication/{{instanceId}}/RaiseCustomerDecisionCompleted
Content-Type: application/json

true

###

POST https://localhost:49256/LoanApplication/{{instanceId}}/RaiseActivity_1ag39siCompleted
Content-Type: application/json

{
}


### 

#@instanceId = {{startLoanApplication.response.body.$}}

POST https://localhost:49256/LoanApplication/{{instanceId}}/RaiseActivity_1mp2kplCompleted
Content-Type: application/json

{
}
